name: Build Status
on:
  push:
    branches:
      - master
jobs:
  build-and-test-windows:
    name: Build And Test
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          8.0.x
          10.0.x

    - name: Generate Classes
      run: dotnet run -c Release -f net8.0 -p tools\NHapiTools.Generator\NHapiTools.Generator.csproj

    - name: Install dependencies
      run: dotnet restore

    - name: Initial Build
      run: dotnet build -c Release --no-restore

    - name: Run tests for all target frameworks
      run: | 
        dotnet test -c Debug -f net462 --no-restore -r TestResults
        dotnet test -c Debug -f net8.0 --no-restore -r TestResults
        dotnet test -c Debug -f net10.0 --no-restore -r TestResults

    - name: NuGet Pack
      run: NuGet.exe pack NHapiTools.nuspec
      working-directory: tools\nuget
